name: Build Linux Binaries for x64

on:
  push:
    branches: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_JSON_PATH: ${{ github.workspace }}/package.json # Define path to package.json
    steps:
      - uses: actions/checkout@v3
      - name: Extract package data
        run: |
          echo "APP_NAME=$(jq -r .name $PACKAGE_JSON_PATH)" >> $GITHUB_ENV
          echo "APP_VERSION=$(jq -r .version $PACKAGE_JSON_PATH | tr '-' '_')" >> $GITHUB_ENV
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build x64
        run: npm run build:x64
      - name: Test artifact was created
        run: |
          test -f dist/installers/${{ env.APP_NAME }}_${{ env.APP_VERSION }}_amd64.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_amd64
          path: dist/installers/${{ env.APP_NAME }}_${{ env.APP_VERSION }}_amd64.deb
