name: Build Linux Binaries for arm64
on:
  push:
    branches:
      - "build"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_JSON_PATH: ${{ github.workspace }}/package.json # Define path to package.json
    steps:
      - uses: actions/checkout@v3
      - name: Extract package data
        run: |
          echo "APP_NAME=$(jq -r .name $PACKAGE_JSON_PATH)" >> $GITHUB_ENV
          echo "APP_VERSION=$(jq -r .version $PACKAGE_JSON_PATH)" >> $GITHUB_ENV
      - name: Arm Build
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: "raspios_lite_arm64:latest"
          cpu: "cortex-a53"
          image_additional_mb: 5000
          copy_artifact_path: dist/installers/${{ env.APP_NAME }}_${{ env.APP_VERSION }}_arm64.deb
          commands: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
            pwd
            npm ci
            npm run lint
            npm run build:arm64
      - name: Test artifact was copied
        run: |
          test -f ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_arm64.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_arm64
          path: ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_arm64.deb
