name: Build Linux Binaries for arm64
on:
  push:
    branches:
      - "build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Arm Build
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: "raspios_lite_arm64:latest"
          cpu: "cortex-a53"
          image_additional_mb: 5000
          copy_artifact_path: dist/installers/lanternflytv_0.0.1_arm64.deb
          commands: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
            pwd
            npm ci
            npm run lint
            npm run build:arm64
      - name: Test artifact was copied
        run: |
          test -f lanternflytv_0.0.1_arm64.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lanternflytv_0.0.1_arm64
          path: lanternflytv_0.0.1_arm64.deb
