name: Test arm-runner-action artifact copy
on:
  push:
    branches:
      - "build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Arm Build
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: "raspios_lite_arm64:latest"
          cpu: "cortex-a53"
          copy_artifact_path: dist/installers/artifact.txt
          commands: |
            mkdir -p dist/installers
            echo "This is a test artifact created in ARM environment." > dist/installers/artifact.txt
      - name: Test artifact was copied
        run: |
          test -f artifact.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact.txt
