name: Build Linux Binaries for x64

on:
  push:
    branches: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build x64
        run: npm run build:x64
      - name: Archive production artifacts
        run: |
          tar -czvf dist/installers/package-lanternfly-x64.tar.gz dist/installers/lanternflytv_*.deb
          echo "ls -R dist/installers: "
          ls -R dist/installers
      - name: Debug production artifacts
        run: |
          pwd
          echo "ls dist/installers: "
          ls dist/installers
          echo "Artifact name: package-lanternfly-x64"
          echo "Artifact path: dist/installers/package-lanternfly-x64.tar.gz"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-lanternfly-x64
          path: dist/installers/package-lanternfly-x64.tar.gz
