name: Build Linux Binaries for x64

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build x64
        run: npm run build:x64
      - name: Archive production artifacts
        run: |
          cd dist/installers
          tar -czvf package-lanternflytv-x64.tar.gz lanternflytv_*.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-lanternflytv-x64
          path: dist/installers/package-lanternflytv-x64.tar.gz
