name: Build Linux Binaries for arm64

on:
  push:
    branches: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Arm Build
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          cpu: cortex-a53
          image_additional_mb: 5000
          copy_artifact_path: dist/installers/*.tar.gz
          copy_artifact_dest: artifacts
          exit_on_fail: false
          commands: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
            pwd
            npm ci
            npm run lint
            npm run build:arm64
            tar -czvf dist/installers/package-lanternfly-arm64.tar.gz dist/installers/lanternflytv_*.deb
            echo "ls -R dist/installers: "
            ls -R dist/installers
      - name: Debug production artifacts
        run: |
          pwd
          echo "ls artifacts: "
          ls artifacts
          echo "ls ../artifacts: "
          ls ../artifacts
          echo "Artifact name: package-lanternfly-arm64"
          echo "Artifact path: artifacts"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-lanternfly-arm64
          path: artifacts
